/* ═══════════════════════════════════════════════
   Caderno RD · semana-02.js · Hábitos + Procrastinação
   ═══════════════════════════════════════════════ */

window.SEMANA_DATA = {
  numero: 2,
  titulo: 'Hábitos + Procrastinação',
  temaShort: 'Hábitos',
  sprint: 'Sprint 3 · Módulo 8',
  icon: 'ti-refresh',
  tagClass: 'habitos',

  experimento: {
    titulo: 'Identificar e ancorar um hábito',
    descricao: 'Escolha um hábito pequeno que você quer criar. Identifique um comportamento que você já faz todo dia — o hábito âncora. Conecte o novo hábito logo depois desse comportamento existente. Ex: "Depois de lavar o rosto, vou escrever 1 linha no caderno." Não tente criar um hábito grande — tente criar um gatilho confiável para um hábito minúsculo.',
    placeholder_obs: 'O que você escolheu? Funcionou o gatilho hoje?',
  },

  dias: [
    {
      numero: 1,
      titulo: 'Por que 21 dias é um mito — e o que a ciência realmente diz',
      subtitulo: 'A neurociência dos hábitos e o tempo real de formação',
      aula: 'Aula 052 · A neurociência dos hábitos (69 min)',
      resumo: 'Eslen desmonta o mito dos 21 dias com o estudo de Lally et al. (2010), que acompanhou pessoas reais formando hábitos na vida cotidiana. A média foi de 66 dias — com variação enorme de 18 a 254 dias. O mais importante não é o número: é entender que hábitos seguem uma curva assintótica — os maiores ganhos acontecem no início, e perder um dia ocasional não desfaz o progresso acumulado.',
      ancora: {
        badge: 'Semana 2',
        titulo: 'Loop do hábito — gatilho, rotina e recompensa',
        desc: 'Todo hábito tem três componentes: um gatilho (o que dispara o comportamento), uma rotina (o comportamento em si) e uma recompensa (o que o cérebro registra como valioso). Para criar um hábito, não tente ter mais força de vontade — torne o gatilho mais óbvio e a recompensa mais imediata. Para quebrar um hábito, ataque o gatilho ou troque a rotina.',
      },
      artigo: {
        nome: 'How Are Habits Formed: Modelling Habit Formation in the Real World',
        fonte: 'Lally et al. · <em>European Journal of Social Psychology</em>, 2010',
        focal: 'Foque na <strong>curva de automaticidade</strong> e no que determina a velocidade de formação de um hábito. Os dados sobre perder dias ocasionais são especialmente importantes — contradizem o que a maioria das pessoas acredita.',
        frase: '"Missing a single opportunity to perform the behaviour did not materially affect the habit formation process."',
        frase_fonte: 'Lally et al., 2010 · um dia perdido não desfaz o hábito',
      },
      reflexao: {
        contexto: 'Pensa em hábitos que você tentou criar e não conseguiu manter. E em hábitos que você tem hoje sem nem perceber — que simplesmente acontecem.',
        pergunta: 'O que é diferente entre os hábitos que ficaram e os que não ficaram? Qual era o gatilho, a rotina e a recompensa de cada um? O que isso te diz sobre como você funciona?',
        modos: ['escrever', 'lista'],
        placeholder_escrever: 'Analisa dois ou três hábitos — um que funcionou, um que não funcionou. O que era diferente?',
        placeholder_lista: 'Hábito que ficou: gatilho / rotina / recompensa\nHábito que não ficou: o que faltou?',
        hint: 'Não se trata de motivação ou disciplina — se trata de design. O hábito que não ficou provavelmente tinha um gatilho fraco ou uma recompensa adiada demais.',
      },
      tcc: {
        titulo: 'Crenças sobre força de vontade e hábitos',
        campos: ['Pensamento automático', 'Crença central que alimenta', 'Evidência contra', 'Pensamento mais preciso'],
        placeholders: [
          'Ex: "Não consigo criar hábitos porque não tenho disciplina"...',
          'Ex: "Pessoas disciplinadas são assim por natureza — eu não sou"...',
          'O que Lally et al. mostram sobre o papel do design vs. força de vontade?',
          'Uma versão que coloca a responsabilidade no sistema, não no caráter.',
        ],
        hint: 'A ciência dos hábitos é essencialmente uma ciência de design de ambiente — não de caráter.',
      },
      materiais: [
        { tipo: 'livro', titulo: 'Hábitos Atômicos — Clear · Caps. 1 e 2', detalhe: 'James Clear · A melhor introdução prática à ciência dos hábitos', principal: true },
        { tipo: 'video', titulo: 'The Power of Habit — Charles Duhigg · TED Talk', detalhe: '15 min · O loop do hábito explicado com exemplos concretos', principal: false },
      ],
      conceito_revisao: 'Loop do hábito (gatilho-rotina-recompensa) e os verdadeiros 66 dias',
    },
    {
      numero: 2,
      titulo: 'Como sair do automatismo',
      subtitulo: 'Neuroplasticidade aplicada à mudança de comportamento',
      aula: 'Aula 146 · Como sair do automatismo (25 min)',
      resumo: 'A maioria dos nossos comportamentos opera no piloto automático — o que é eficiente, mas pode nos prender em padrões que não escolhemos conscientemente. Sair do automatismo requer ativação do córtex pré-frontal: notar o comportamento, criar fricção antes de executá-lo e introduzir uma pausa deliberada. Eslen discute ferramentas práticas para aumentar a consciência comportamental sem depender de força de vontade.',
      ancora: {
        badge: 'Semana 2',
        titulo: 'Neuroplasticidade — o cérebro muda com a experiência',
        desc: 'O estudo dos taxistas de Londres (Maguire et al.) mostrou que aprendizado intensivo produz mudanças estruturais mensuráveis no hipocampo adulto. Isso não é metáfora — é volume de tecido cerebral. Cada comportamento repetido fortalece sua rede neural correspondente. Cada comportamento abandonado enfraquece. "Use ou perca" não é clichê: é biologia.',
      },
      artigo: {
        nome: 'Acquiring "the Knowledge" of London\'s Layout Drives Structural Brain Changes',
        fonte: 'Maguire et al. · <em>PNAS</em>, 2000',
        focal: 'Foque no <strong>mecanismo pelo qual a prática repetida produz mudança estrutural cerebral</strong>. A implicação prática: hábitos não são apenas psicológicos — eles literalmente remodeiam o cérebro.',
        frase: '"The hippocampus of licensed taxi drivers was significantly larger in its posterior region than in controls — and correlated with time spent as a taxi driver."',
        frase_fonte: 'Maguire et al., 2000',
      },
      reflexao: {
        contexto: 'Pensa nos seus comportamentos automáticos do dia a dia — os que acontecem sem você decidir conscientemente. Alguns provavelmente te servem bem. Outros talvez não.',
        pergunta: 'Qual comportamento automático você mais gostaria de mudar? O que o dispara? Em que momento você poderia inserir uma pausa consciente antes de executá-lo?',
        modos: ['escrever', 'diagrama'],
        placeholder_escrever: 'Descreve o comportamento, o gatilho, o que acontece no automatismo, e onde você poderia criar uma pausa.',
        diagrama_hint: 'Mapeie: gatilho → comportamento automático → consequência. Onde inserir a pausa?',
        hint: 'Sair do automatismo não requer força de vontade na hora — requer design antes da hora.',
      },
      tcc: null,
      materiais: [
        { tipo: 'livro', titulo: 'Hábitos Atômicos — Clear · Cap. 4: O Homem Que Não Parecia Ter uma Memória', detalhe: 'James Clear · Sobre automaticidade e como os hábitos operam sem consciência', principal: true },
        { tipo: 'podcast', titulo: 'Huberman Lab — How to Change Your Habits', detalhe: 'Andrew Huberman · Neuroplasticidade aplicada à mudança comportamental', principal: false },
      ],
      conceito_revisao: 'Neuroplasticidade — comportamentos repetidos remodelam o cérebro literalmente',
    },
    {
      numero: 3,
      titulo: 'Procrastinação não é preguiça — é regulação emocional',
      subtitulo: 'O que a neurociência revela sobre o adiamento crônico',
      aula: 'Aula 044 · Como reduzir a procrastinação (passo a passo) (51 min)',
      resumo: 'Steel e Klingsieck chegaram a uma conclusão que contradiz a maioria dos livros de produtividade: procrastinação não é um problema de gerenciamento de tempo. É um problema de regulação emocional — especificamente, evitação de estados emocionais negativos associados a uma tarefa. Ansiedade, tédio, medo de falhar, sensação de incompetência. Entender isso muda completamente a abordagem: cobrar mais disciplina de si mesmo é a estratégia menos eficaz.',
      ancora: {
        badge: 'Semana 2',
        titulo: 'Procrastinação como evitação emocional',
        desc: 'Quando você evita uma tarefa, não está evitando o trabalho — está evitando o estado emocional que o trabalho provoca: ansiedade de não saber por onde começar, medo de produzir algo ruim, tédio de uma tarefa sem sentido. A solução não é "ser mais disciplinado" — é tornar o início emocionalmente seguro e a recompensa mais imediata.',
      },
      artigo: {
        nome: 'Understanding and Treating Procrastination: A Review of a Common Self-Regulatory Failure',
        fonte: 'Steel & Klingsieck · <em>Australian Psychologist</em>, 2016',
        focal: 'Foque na <strong>Temporal Motivation Theory</strong> e na distinção entre procrastinação como falha de regulação emocional vs. gerenciamento de tempo. A equação de motivação temporal é especialmente útil — entender cada variável ajuda a identificar onde intervir.',
        frase: '"Procrastination is not a time management problem — it is an emotion regulation problem."',
        frase_fonte: 'Steel & Klingsieck, 2016',
      },
      reflexao: {
        contexto: 'Pensa nas tarefas que você mais procrastina. Não as mais difíceis — às vezes procrastinamos coisas simples e fazemos coisas difíceis sem pensar.',
        pergunta: 'Qual emoção está por trás da sua procrastinação mais frequente? Medo de falhar? Ansiedade de não saber como começar? Tédio? Sensação de que não fará bem feito? Seja específico — o nome da emoção importa.',
        modos: ['escrever', 'lista'],
        placeholder_escrever: 'Descreve uma situação concreta de procrastinação e tenta identificar a emoção que está sendo evitada.',
        placeholder_lista: 'Tarefa que procrastino → emoção que evito → o que tornaria o início mais seguro',
        hint: 'A emoção não precisa desaparecer para você agir — precisa ser reconhecida. Nomeá-la já reduz sua intensidade.',
      },
      tcc: {
        titulo: 'Crenças por trás da procrastinação',
        campos: ['Pensamento automático antes da tarefa', 'Emoção que esse pensamento provoca', 'Crença central que alimenta', 'Pensamento que tornaria o início mais fácil'],
        placeholders: [
          'Ex: "Preciso estar no estado certo para começar", "Não vou fazer bem feito mesmo"...',
          'Ex: Ansiedade, vergonha antecipada, tédio, sobrecarga...',
          'Ex: "Só vale se for perfeito", "Se eu falhar, significa que sou incompetente"...',
          'Ex: "Não preciso terminar hoje — só preciso começar por 5 minutos."',
        ],
        hint: 'Perfecionismo e procrastinação são quase sempre parceiros. A crença "só vale se for ótimo" garante que o início nunca chegue.',
      },
      materiais: [
        { tipo: 'livro', titulo: 'Hábitos Atômicos — Clear · Cap. 11: A Regra dos Dois Minutos', detalhe: 'James Clear · A técnica mais eficaz para vencer o início — o maior obstáculo da procrastinação', principal: true },
        { tipo: 'video', titulo: 'Inside the Mind of a Master Procrastinator — Tim Urban · TED', detalhe: '14 min · A representação mais honesta e hilária do loop da procrastinação', principal: false },
      ],
      conceito_revisao: 'Procrastinação é evitação emocional — cobrar disciplina é a estratégia menos eficaz',
    },
    {
      numero: 4,
      titulo: 'O cérebro que prefere agora',
      subtitulo: 'Desconto temporal e a guerra entre o eu de hoje e o eu do futuro',
      aula: 'Aula 153 · Desconto temporal da recompensa (e o longo prazo) (30 min)',
      resumo: 'McClure et al. documentaram que o sistema límbico e o córtex pré-frontal literalmente competem quando recompensas imediatas estão disponíveis. O sistema límbico domina o agora; o PFC representa o futuro. Quando você escolhe o Netflix em vez de estudar, não é falta de caráter — é uma batalha neural em que o imediato tem vantagem estrutural. Eslen explora como o desconto hiperbólico explica por que o futuro parece sempre menos atraente do que deveria.',
      ancora: {
        badge: 'Semana 2',
        titulo: 'Desconto temporal — por que "agora" sempre parece mais valioso',
        desc: 'Desconto hiperbólico é a tendência de desvalorizar recompensas futuras de forma desproporcional. Uma recompensa daqui a 30 dias parece muito menos valiosa do que parece quando o dia chega. Isso não é irracionalidade — é uma característica do sistema neural humano. A implicação prática: para mudar comportamento, torne as recompensas do comportamento desejado mais imediatas e as do comportamento indesejado mais presentes.',
      },
      artigo: {
        nome: 'Separate Neural Systems Value Immediate and Delayed Monetary Rewards',
        fonte: 'McClure et al. · <em>Science</em>, 2004',
        focal: 'Foque no <strong>mecanismo de competição entre sistema límbico e PFC</strong> ao avaliar recompensas imediatas vs. futuras. A implicação comportamental é mais importante que os detalhes metodológicos.',
        frase: '"When immediate rewards are available, the limbic system dominates — providing the neural basis for impulsive choice."',
        frase_fonte: 'McClure et al., 2004',
      },
      reflexao: {
        contexto: 'Pensa em situações onde você sabe o que deveria fazer, mas não faz — e a alternativa que escolhe tem recompensa imediata e custo futuro.',
        pergunta: 'Em quais áreas da sua vida o desconto temporal está te custando mais? O que o "eu do futuro" vai agradecer ou reclamar das escolhas que o "eu de hoje" está fazendo?',
        modos: ['escrever', 'lista'],
        placeholder_escrever: 'Descreve uma área onde essa tensão é mais evidente na sua vida agora.',
        placeholder_lista: 'Áreas onde prefiro o agora → o que o eu do futuro gostaria que fosse diferente → o que tornaria o futuro mais presente hoje',
        hint: 'Não é sobre ter mais força de vontade. É sobre redesenhar o ambiente para que o comportamento desejado tenha recompensa mais imediata.',
      },
      tcc: null,
      materiais: [
        { tipo: 'livro', titulo: 'Hábitos Atômicos — Clear · Cap. 6: A regra do cartão de identidade', detalhe: 'James Clear · Como tornar a identidade futura mais presente no presente', principal: true },
        { tipo: 'livro', titulo: 'Antifragil — Taleb · Cap. sobre optionality e longo prazo', detalhe: 'Nassim Taleb · Uma perspectiva diferente sobre como valorizar o futuro', principal: false },
      ],
      conceito_revisao: 'Desconto temporal — sistema límbico (agora) vs. PFC (futuro) em competição neural',
    },
    {
      numero: 5,
      titulo: 'Seu ambiente decide por você',
      subtitulo: 'Design de contexto como ferramenta mais poderosa que a disciplina',
      aula: 'Aula 022 · Como modular seu microambiente (38 min)',
      resumo: 'Eslen constrói o argumento de que a maioria das decisões que acreditamos tomar conscientemente são na verdade determinadas pelo ambiente ao nosso redor. Não porque somos autômatos — mas porque o Sistema 1 responde ao contexto antes que o Sistema 2 sequer perceba o que aconteceu. A consequência prática é poderosa: mudar o ambiente é mais eficaz e mais sustentável do que tentar mudar a vontade.',
      ancora: {
        badge: 'Semana 2',
        titulo: 'Fricção e fluidez — como o ambiente molda o comportamento',
        desc: 'Hábitos bons ficam mais prováveis quando têm fricção mínima — o tênis perto da cama, o livro na mesa, o celular em outro quarto. Hábitos ruins ficam menos prováveis quando têm fricção máxima — apagar o aplicativo, deixar o chocolate em outra prateleira, colocar o carregador longe da cama. Cada ponto de fricção ou fluidez que você adiciona ao ambiente está literalmente votando no comportamento que vai acontecer.',
      },
      artigo: {
        nome: 'How Are Habits Formed: Modelling Habit Formation in the Real World',
        fonte: 'Lally et al. · <em>European Journal of Social Psychology</em>, 2010',
        focal: 'Releia com foco no papel do <strong>contexto e do ambiente na formação de hábitos</strong>. O contexto estável é o maior preditor de automaticidade — mais do que a motivação ou a intenção.',
        frase: '"Context stability is a key factor in habit formation — behaviours that occur in consistent contexts become more automatic over time."',
        frase_fonte: 'Lally et al., 2010',
      },
      reflexao: {
        contexto: 'Pensa no seu ambiente imediato — o quarto, a mesa de estudo, o celular, os aplicativos abertos, o que está à vista quando você chega em casa.',
        pergunta: 'Quais elementos do seu ambiente atual estão facilitando comportamentos que você não quer? E quais mudanças de ambiente — por menores que sejam — poderiam fazer o comportamento desejado acontecer quase sem esforço?',
        modos: ['escrever', 'lista'],
        placeholder_escrever: 'Descreve seu ambiente atual e identifica pontos de fricção e fluidez para comportamentos bons e ruins.',
        placeholder_lista: 'Comportamento que quero criar → o que mudaria no ambiente → comportamento que quero reduzir → que fricção adicionaria',
        hint: 'A menor mudança de ambiente que você realmente vai fazer vale mais que o design perfeito que vai ficar no papel.',
      },
      tcc: {
        titulo: 'Crenças sobre controle e ambiente',
        campos: ['Pensamento automático', 'Crença central', 'Evidência contra', 'Experimento de design de ambiente'],
        placeholders: [
          'Ex: "Eu deveria conseguir resistir sem precisar mudar o ambiente"...',
          'Ex: "Se eu precisar de truques no ambiente, é porque sou fraco"...',
          'O que a ciência comportamental mostra sobre o papel do ambiente vs. força de vontade?',
          'Uma mudança de ambiente pequena que você vai testar essa semana.',
        ],
        hint: 'Engenheiros não culpam os usuários quando um produto é difícil de usar — eles redesenham o produto. Você pode fazer o mesmo com seu ambiente.',
      },
      materiais: [
        { tipo: 'livro', titulo: 'Hábitos Atômicos — Caps. 6, 7 e 8', detalhe: 'James Clear · O capítulo mais prático do livro — design de ambiente completo', principal: true },
        { tipo: 'livro', titulo: 'O Poder do Hábito — Duhigg · Cap. 5', detalhe: 'Charles Duhigg · Como Starbucks ensinou força de vontade — sobre fricção e contexto', principal: false },
      ],
      conceito_revisao: 'Design de ambiente — fricção e fluidez determinam o comportamento mais que a vontade',
    },
    {
      numero: 6,
      titulo: 'Você é orquídea, tulipa ou dente-de-leão?',
      subtitulo: 'Por que a mesma estratégia funciona para uns e não para outros',
      aula: 'Aulas 136/137 · O gene determina o comportamento (30 + 20 min)',
      resumo: 'Lionetti e colaboradores propuseram um modelo tripartite de sensibilidade ambiental que revoluciona como pensamos sobre diferenças individuais. Dentes-de-leão (baixa sensibilidade) prosperam em quase qualquer ambiente. Tulipas (média) são a maioria. Orquídeas (alta sensibilidade) reagem intensamente tanto a ambientes negativos quanto positivos — elas sofrem mais em ambientes ruins e florescem mais em ambientes bons. Esse modelo explica por que "uma solução para todos" raramente funciona em mudança comportamental.',
      ancora: {
        badge: 'Semana 2',
        titulo: 'Sensibilidade diferencial — orquídea, tulipa ou dente-de-leão',
        desc: 'Saber seu perfil de sensibilidade muda a forma como você deve projetar hábitos e estratégias. Uma orquídea em ambiente caótico vai sofrer muito mais que um dente-de-leão — e vai florescer muito mais em ambiente estruturado. Não se trata de fraqueza ou força: é biologia. E é informação útil para design comportamental.',
      },
      artigo: {
        nome: 'Dandelions, Tulips and Orchids: Evidence for the Existence of Low-Sensitive, Medium-Sensitive and High-Sensitive Individuals',
        fonte: 'Lionetti et al. · <em>Translational Psychiatry</em>, 2018',
        focal: 'Foque em entender os <strong>três perfis e suas implicações práticas</strong> para mudança comportamental e design de ambiente. As implicações para intervenção são mais relevantes que os dados genéticos aqui.',
        frase: '"High-sensitive individuals are more reactive to both negative and positive environments — they are not simply more vulnerable, but more plastic."',
        frase_fonte: 'Lionetti et al., 2018',
      },
      reflexao: {
        contexto: 'Pensa em como você responde a ambientes diferentes: ambientes caóticos vs. organizados, com pressão vs. sem pressão, com apoio social vs. isolado.',
        pergunta: 'Com qual perfil você mais se identifica — e o que isso implica para o design dos seus hábitos e estratégias de mudança? O que você deveria parar de fazer porque não combina com sua sensibilidade, e o que deveria começar?',
        modos: ['escrever', 'lista'],
        placeholder_escrever: 'Descreve como você responde a ambientes diferentes e o que seu perfil de sensibilidade implica para seus hábitos.',
        placeholder_lista: 'Meu perfil: orquídea / tulipa / dente-de-leão\nAmbientes que me fazem funcionar bem:\nAmbientes que me drenam:\nImplicações para meus hábitos:',
        hint: 'Não existe perfil melhor. Existe saber quem você é e projetar sua vida de acordo.',
      },
      tcc: null,
      materiais: [
        { tipo: 'artigo', titulo: 'Vantage Sensitivity — Pluess & Belsky (Psychological Bulletin, 2013)', detalhe: 'Por que algumas pessoas se beneficiam desproporcionalmente de intervenções positivas', principal: true },
        { tipo: 'livro', titulo: 'O Poder do Hábito — Duhigg · Cap. sobre identidade e hábitos-chave', detalhe: 'Charles Duhigg · Como conhecer seu perfil muda a estratégia de mudança', principal: false },
      ],
      conceito_revisao: 'Sensibilidade diferencial — a estratégia certa depende de quem você é',
    },
    {
      numero: 7,
      titulo: 'O que ficou dessa semana',
      subtitulo: 'Da teoria ao sistema — integrando sono, hábitos e procrastinação',
      aula: 'Dia de integração — sem aula nova',
      resumo: 'Você estudou a neurociência dos hábitos, a saída do automatismo, a procrastinação como regulação emocional, o desconto temporal, o design de ambiente e as diferenças individuais de sensibilidade. Hoje é o momento de conectar tudo isso — e especialmente de integrar com o que aprendeu na semana 1 sobre sono.',
      ancora: {
        badge: 'Semana 2',
        titulo: 'Sono e hábitos são um sistema integrado',
        desc: 'O que a semana 2 revela quando combinada com a semana 1: sono ruim compromete o PFC, que é exatamente o órgão responsável por resistir a impulsos, planejar hábitos e adiar gratificação. Procrastinação piora com sono ruim. Hábitos são mais difíceis de manter quando o PFC está comprometido. Tudo isso é o mesmo sistema.',
      },
      artigo: {
        nome: 'Revisão dos artigos da semana',
        fonte: 'Lally (2010) · Maguire (2000) · Steel & Klingsieck (2016) · McClure (2004) · Lionetti (2018)',
        focal: 'Releia as frases que você carregou durante a semana. Qual delas mudou mais a forma como você pensa sobre seus hábitos e procrastinação?',
        frase: '"You do not rise to the level of your goals. You fall to the level of your systems."',
        frase_fonte: 'James Clear — Hábitos Atômicos',
      },
      reflexao: {
        contexto: 'Duas semanas de estudo. Sono na semana 1, hábitos e procrastinação na semana 2. Você tem dados do check-in de 14 dias.',
        pergunta: 'Qual é a conexão mais importante que você vê entre o que aprendeu nas duas semanas? E qual seria o sistema mais simples possível que melhoraria tanto seu sono quanto seus hábitos ao mesmo tempo?',
        modos: ['escrever'],
        placeholder_escrever: 'Descreve o sistema — não os objetivos. Um conjunto de comportamentos e ambientes que funcionariam em conjunto.',
        hint: 'Um sistema que você vai realmente usar amanhã vale mais que um sistema perfeito que vai ficar no papel.',
      },
      tcc: null,
      materiais: [
        { tipo: 'livro', titulo: 'Hábitos Atômicos — Clear · Cap. 19 e Conclusão', detalhe: 'James Clear · Como tudo se conecta num sistema integrado de melhoria contínua', principal: true },
        { tipo: 'livro', titulo: 'GTD — Getting Things Done · Cap. 1', detalhe: 'David Allen · O sistema que mais complementa a ciência dos hábitos para pessoas com alta demanda cognitiva', principal: false },
      ],
      conceito_revisao: 'Sono e hábitos são um sistema integrado — tudo converge para o PFC',
    },
  ],

  reflexao_semanal: {
    titulo: 'Hábitos como sistema — o que você vai construir',
    subtitulo: 'Integrando sono (S1) e hábitos (S2) antes de avançar',
    secoes: [
      {
        titulo: '1. O que mudou desde a semana 1',
        prompt: 'Olhe para os check-ins das duas semanas. O que mudou — mesmo que seja sutil? O que permanece igual? O que você esperava que fosse diferente?',
        placeholder: 'Compare os padrões das duas semanas. Não precisa ter melhorado — só precisa ter observado.',
      },
      {
        titulo: '2. Sua procrastinação tem nome',
        prompt: 'Depois de estudar procrastinação como regulação emocional, você consegue nomear a emoção central que está por trás da sua procrastinação mais frequente? O que especificamente você está evitando?',
        placeholder: 'Seja específico — o nome da emoção e a tarefa ou situação que a provoca.',
      },
      {
        titulo: '3. Seu perfil de sensibilidade e seus hábitos',
        prompt: 'Como seu perfil (orquídea, tulipa ou dente-de-leão) afeta a forma como você deveria projetar seus hábitos? O que isso muda na prática — no ambiente, na rotina, nas expectativas?',
        placeholder: 'Implicações concretas do seu perfil para o design dos seus hábitos.',
      },
      {
        titulo: '4. O sistema mínimo viável',
        prompt: 'Se você fosse projetar o sistema mais simples possível que melhorasse sono E hábitos ao mesmo tempo, com o menor esforço possível, como seria? Pense em âncoras, gatilhos, ambiente.',
        placeholder: 'Descreve o sistema — máximo 3 elementos. Se for complicado demais, está errado.',
      },
      {
        titulo: '5. O que levar para a Semana 3 — Motivação + Sistema de Recompensa',
        prompt: 'A semana 3 vai entrar em motivação intrínseca, o conceito de suco do Eslen, e o sistema dopaminérgico. O que das semanas 1 e 2 já se conecta com esses temas?',
        placeholder: 'Antecipações, perguntas, o que você já percebe sobre sua própria motivação.',
      },
    ],
  },
};
