/* ═══════════════════════════════════════════════
   Caderno RD · semana-01.js · Sono
   ═══════════════════════════════════════════════ */

window.SEMANA_DATA = {
  numero: 1,
  titulo: 'Sono — A Fundação',
  temaShort: 'Sono',
  sprint: 'Sprint 1 · Módulo 4',
  emoji: '🌙',
  tagClass: 'sono',

  experimento: {
    titulo: 'Telas off 30 min antes de dormir',
    descricao: 'Escolha um horário fixo para apagar todas as telas esta semana — mesmo que seja 30 minutos antes do que você costuma dormir. Não precisa ser perfeito nem todos os dias. Observe o que acontece com a qualidade do sono e com seu estado na manhã seguinte. Não mude mais nada além disso.',
    placeholder_obs: 'O que aconteceu? Conseguiu? O que observou?',
  },

  dias: [
    {
      numero: 1,
      titulo: 'O cérebro que você leva pro plantão',
      subtitulo: 'Quando privação de sono não é fadiga — é neurobiologia mensurável',
      aula: 'Aula 049 · O cérebro de quem dorme mal (66 min)',
      resumo: 'A privação de sono não é apenas cansaço subjetivo: ela produz uma alteração neurobiológica mensurável em que a amígdala fica até 60% mais reativa enquanto o córtex pré-frontal perde a conexão que normalmente a regula. O resultado é um cérebro que reage mais, decide pior e retém menos. Eslen usa esse dado não como alarmismo, mas como argumento de que sono é pré-requisito fisiológico — não variável ajustável conforme a agenda.',
      ancora: {
        badge: 'Semana 1',
        titulo: 'Desconexão PFC → Amígdala',
        desc: 'Com sono adequado, o PFC age como freio da amígdala — avalia, contextualiza, inibe reações automáticas. Sem sono, esse freio se solta. Não é fraqueza de caráter reagir mal depois de uma noite ruim; é arquitetura neural operando no limite. Internalizar isso muda a relação com os próprios erros — e com os dos outros.',
      },
      artigo: {
        nome: 'The Sleep-Deprived Human Brain',
        fonte: 'Krause et al. · <em>Nature Reviews Neuroscience</em>, 2017',
        focal: 'Foque em entender o <strong>mecanismo da desconexão PFC-amígdala</strong> e suas consequências para tomada de decisão. A Figura 1 vale mais que qualquer parágrafo — olhe ela primeiro.',
        frase: '"Sleep loss amplifies negative emotional reactivity and blunts the prefrontal control that would otherwise temper it."',
        frase_fonte: 'Krause et al., 2017 · carregue essa frase pela semana',
      },
      reflexao: {
        contexto: 'Pensa nas últimas semanas. Não no pior plantão — num dia qualquer de rotina. Quantas horas você dormiu na noite anterior às situações que mais te custaram emocionalmente?',
        pergunta: 'Como seria diferente sua resposta emocional a situações difíceis se você tivesse dormido 7h? O que especificamente mudaria — no humor, na paciência, nas decisões?',
        modos: ['escrever', 'diagrama', 'lista'],
        placeholder_escrever: 'Sem filtro, sem julgamento. Ninguém lê isso além de você.',
        placeholder_lista: '3 situações recentes:\n1. O que aconteceu → o que poderia ter sido diferente\n2. ...\n3. ...',
        diagrama_hint: 'Dois estados: você com pouco sono × você com sono suficiente',
        hint: 'Não force uma resposta "correta". A honestidade aqui é o exercício.',
      },
      tcc: {
        titulo: 'Crenças sobre sono e produtividade',
        campos: ['Pensamento automático', 'Crença central que alimenta', 'Evidência contra', 'Pensamento mais adaptativo'],
        placeholders: [
          'Ex: "Não tenho tempo pra dormir 7h", "Descansar é perder tempo"...',
          'Ex: "Preciso ser produtivo o tempo todo"...',
          'O que a ciência e sua experiência dizem de diferente?',
          'Não precisa ser positivo — só mais preciso.',
        ],
        hint: 'Se não aparecer nada agora, deixa em branco. A observação às vezes vem depois.',
      },
      materiais: [
        { tipo: 'video', titulo: 'Sleep is your superpower — Matthew Walker', detalhe: 'TED Talk · 19 min · O ponto de entrada mais denso e claro sobre o tema', principal: true },
        { tipo: 'capitulo', titulo: 'Hábitos Atômicos — Cap. 5: A melhor forma de começar', detalhe: 'James Clear · Habit stacking aplicado a âncoras de sono', principal: false },
      ],
      conceito_revisao: 'Desconexão PFC-Amígdala — privação amplifica reatividade emocional',
    },
    {
      numero: 2,
      titulo: 'A mente que não para',
      subtitulo: 'Por que noites ruins viram dias de ruminação',
      aula: 'Aula 145 · Dormir mal e pensamentos intrusivos (22 min)',
      resumo: 'Quando o PFC está comprometido pela privação de sono, ele perde capacidade de inibir o hipocampo durante tentativas de suprimir memórias e pensamentos indesejados. O resultado é que a mente fica em loop: memórias que você tentou deixar de lado voltam com mais força. Ruminação noturna não é fraqueza psicológica — é neurobiologia. Eslen conecta isso à importância do sono como ferramenta de regulação emocional ativa.',
      ancora: {
        badge: 'Semana 1',
        titulo: 'Supressão de pensamentos sob privação de sono',
        desc: 'O mecanismo que inibe pensamentos indesejados depende de comunicação eficiente entre PFC e hipocampo. Sono ruim quebra essa comunicação. Tentar "parar de pensar" funciona mal em qualquer circunstância — mas funciona muito pior privado de sono. Reconhecer isso é o primeiro passo para não travar num ciclo de autocobrança desnecessária.',
      },
      artigo: {
        nome: 'Losing Control: Sleep Deprivation Impairs the Suppression of Unwanted Thoughts',
        fonte: 'Scullin et al. · <em>Clinical Psychological Science</em>, 2019',
        focal: 'Foque em entender <strong>por que a supressão ativa de pensamentos falha sob privação de sono</strong> — o mecanismo PFC-hipocampo. A seção de resultados comportamentais é mais relevante que a de neuroimagem.',
        frase: '"Sleep deprivation disrupts the executive control needed to keep unwanted memories at bay."',
        frase_fonte: 'Scullin et al., 2019',
      },
      reflexao: {
        contexto: 'Pensa nas últimas noites em que você ficou acordado pensando. Não necessariamente ansiedade aguda — às vezes é só um replay de situações do dia, preocupações difusas, coisas que você "deveria" ter feito.',
        pergunta: 'Quais pensamentos costumam te invadir quando você está privado de sono? O que eles têm em comum? E o que você normalmente faz com eles?',
        modos: ['escrever', 'lista'],
        placeholder_escrever: 'Descreve os pensamentos, os temas recorrentes, e o que você costuma fazer com eles.',
        placeholder_lista: 'Liste os pensamentos mais frequentes. Para cada um: qual a frequência? O que você faz?',
        hint: 'Observação sem julgamento. Não é pra resolver agora — é pra conhecer o padrão.',
      },
      tcc: null,
      materiais: [
        { tipo: 'livro', titulo: 'Por Que Dormimos — Walker · Capítulo 1', detalhe: 'Introdução ao sono como fenômeno biológico fundamental', principal: true },
        { tipo: 'podcast', titulo: 'Huberman Lab — Master Your Sleep & Be More Alert When Awake', detalhe: 'Andrew Huberman · ~1h · Ferramentas práticas baseadas em ciência', principal: false },
      ],
      conceito_revisao: 'Ruminação noturna tem substrato neural — supressão falha sem sono',
    },
    {
      numero: 3,
      titulo: 'Dormir é estudar',
      subtitulo: 'A consolidação de memória que acontece enquanto você não faz nada',
      aula: 'Aulas 007 · Como dormir bem (50 min) + 058 · Como melhorar a memória (44 min)',
      resumo: 'O sono não é uma pausa passiva — é um estado ativo de reorganização neural. Durante o NREM profundo, o hipocampo transfere memórias declarativas para o córtex para armazenamento de longo prazo. Durante o REM, memórias emocionais e procedimentais são consolidadas e integradas. Privar-se de sono após uma sessão de estudo não apenas cansa — compromete a consolidação do que foi aprendido.',
      ancora: {
        badge: 'Semana 1',
        titulo: 'Consolidação de memória — NREM e REM têm papéis distintos',
        desc: 'NREM consolida o factual e declarativo — o que você estudou, leu, viu. REM consolida o emocional e procedimental — como você executa habilidades. Para um residente, estudar a noite toda antes de um dia difícil é biologicamente pior do que estudar menos e dormir.',
      },
      artigo: {
        nome: 'Sleep, Memory, and Plasticity',
        fonte: 'Walker & Stickgold · <em>Annual Review of Psychology</em>, 2006',
        focal: 'Foque em entender as <strong>funções distintas do NREM e REM na consolidação de memória</strong>. A seção "sleep-dependent memory consolidation" é o núcleo — as figuras dos estágios valem mais que o texto.',
        frase: '"Sleep is not merely a passive state of recovery. It is an active process critical for the consolidation of newly acquired memories."',
        frase_fonte: 'Walker & Stickgold, 2006',
      },
      reflexao: {
        contexto: 'Você está numa residência de alta demanda intelectual — aprendendo procedimentos, diagnósticos, protocolos. Tudo isso precisa ser consolidado. E a consolidação, literalmente, acontece enquanto você dorme.',
        pergunta: 'Como você equilibra (ou não) estudo e sono hoje? Que crenças sustentam esse padrão — e o que a ciência do sono muda nessa equação?',
        modos: ['escrever', 'lista'],
        placeholder_escrever: 'Como funciona sua lógica atual de estudo vs. sono?',
        placeholder_lista: 'Liste as crenças que sustentam sacrificar sono por estudo. Quais têm evidência real?',
        hint: 'Sem autocrítica excessiva. O objetivo é clareza, não culpa.',
      },
      tcc: {
        titulo: 'Crenças sobre estudo noturno',
        campos: ['Pensamento automático', 'Crença central que alimenta', 'O que a ciência diz', 'Pensamento mais preciso'],
        placeholders: [
          'Ex: "Se eu dormir, vou perder o conteúdo que acabei de ver"...',
          'Ex: "Só sou bom se me esforço ao máximo"...',
          'O que Walker & Stickgold mostram que contradiz essa crença?',
          'Uma versão que respeita tanto sua ambição quanto a biologia.',
        ],
        hint: 'A crença "estudar mais = aprender mais" é uma das mais arraigadas e mais desafiadas pela ciência do sono.',
      },
      materiais: [
        { tipo: 'livro', titulo: 'Por Que Dormimos — Walker · Capítulo 6', detalhe: 'O capítulo mais relevante para quem estuda — sono e memória acadêmica', principal: true },
        { tipo: 'artigo', titulo: 'Retrieval Practice Produces More Learning — Karpicke & Blunt (Science, 2011)', detalhe: 'Por que testar consolida melhor que reler — e o sono potencializa isso', principal: false },
      ],
      conceito_revisao: 'Sono é consolidação de memória — dormir após estudar não é perda de tempo',
    },
    {
      numero: 4,
      titulo: 'O relógio que você ignora todo dia',
      subtitulo: 'Ritmo circadiano e os sinais que sincronizam seu biológico',
      aula: 'Aula 093 · Luz, comida e exercício — ajuste seu ciclo circadiano (44 min)',
      resumo: 'O núcleo supraquiasmático no hipotálamo age como relógio-mestre e sincroniza praticamente todos os tecidos do corpo com ciclos de ~24h. Ele usa zeitgebers — sincronizadores externos — para se calibrar: luz (o mais poderoso), temperatura, alimentação e exercício. Eslen traduz isso em três alavancas: exposição à luz solar pela manhã, janela de alimentação consistente, e exercício no período matinal ou vespertino.',
      ancora: {
        badge: 'Semana 1',
        titulo: 'Zeitgebers — o que sincroniza seu relógio biológico',
        desc: 'Zeitgeber vem do alemão: "doador de tempo". Luz matinal é o mais potente — 10 a 30 minutos de exposição logo ao acordar ancora o ciclo de melatonina e cortisol. Tela brilhante à noite faz o oposto. Para quem tem rotina irregular como a residência, usar esses sinais intencionalmente é uma das poucas alavancas reais de controle sobre o sono.',
      },
      artigo: {
        nome: 'Rhythms of Life: Circadian Disruption and Brain Disorders Across the Lifespan',
        fonte: 'Frank & Bhaskaran · <em>Nature Reviews Neuroscience</em>, 2017',
        focal: 'Foque em como a <strong>disrupção circadiana crônica se conecta a transtornos mentais e cognitivos</strong>. Os mecanismos são mais importantes que os dados epidemiológicos aqui.',
        frase: '"The brain\'s circadian clock orchestrates the timing of nearly every physiological and psychological process."',
        frase_fonte: 'Frank & Bhaskaran, 2017',
      },
      reflexao: {
        contexto: 'Pensa na sua rotina atual: horários de acordar e dormir, exposição à luz, quando come, quando treina. O quanto ela respeita sinais do seu biológico?',
        pergunta: 'Quais são os principais disruptores do seu ritmo circadiano hoje? Quais você pode controlar — mesmo que minimamente — e quais são impostos pela residência?',
        modos: ['escrever', 'lista'],
        placeholder_escrever: 'Descreve sua rotina real e os maiores conflitos com seu relógio biológico.',
        placeholder_lista: 'Disruptores: o que é estrutural (plantão) × o que é comportamental (escolha)',
        hint: 'O objetivo não é controlar tudo — é identificar onde há margem real de manobra.',
      },
      tcc: null,
      materiais: [
        { tipo: 'podcast', titulo: 'Huberman Lab — Using Light to Optimize Brain Function & Sleep', detalhe: 'Andrew Huberman · ~1h30 · O guia prático mais completo sobre luz e ritmo circadiano', principal: true },
        { tipo: 'capitulo', titulo: 'Hábitos Atômicos — Cap. 6: O ambiente importa mais que a motivação', detalhe: 'James Clear · Design de ambiente aplicado a zeitgebers', principal: false },
      ],
      conceito_revisao: 'Zeitgebers sincronizam seu relógio — luz, alimentação, exercício',
    },
    {
      numero: 5,
      titulo: 'Suas barreiras reais para dormir bem',
      subtitulo: 'Mapear é o primeiro passo para mudar',
      aula: 'Aula 081 · A nova aula 007 — Como dormir bem (18 min)',
      resumo: 'Depois de entender por que o sono importa, Eslen vai pro como. Não é uma lista genérica de higiene do sono — é uma destilação das intervenções com mais evidência: consistência de horário, temperatura do quarto, manejo de luz e cafeína. A mensagem central: a maioria das pessoas que dorme mal não tem um problema de sono — tem um problema de rotina e ambiente.',
      ancora: {
        badge: 'Semana 1',
        titulo: '7 horas não é recomendação — é piso fisiológico',
        desc: 'Watson et al. (2015) estabeleceu que menos de 7h por noite está associado a obesidade, diabetes, hipertensão, AVC e comprometimento cognitivo como relação dose-resposta. "Funcionar bem com menos" é um viés de percepção documentado: pessoas privadas de sono subestimam sistematicamente seu próprio comprometimento.',
      },
      artigo: {
        nome: 'Recommended Amount of Sleep for a Healthy Adult',
        fonte: 'Watson et al. · <em>Sleep</em> / AASM & Sleep Research Society, 2015',
        focal: 'Foque nos <strong>mecanismos que explicam a relação dose-resposta</strong> entre horas de sono e desfechos de saúde. O dado de 7h é o headline — o raciocínio por trás é o que vale internalizar.',
        frase: '"Sleeping less than 7 hours per night is associated with adverse health outcomes — independent of other lifestyle factors."',
        frase_fonte: 'Watson et al., 2015',
      },
      reflexao: {
        contexto: 'Você chegou no dia 5. Ao longo dessa semana, foram surgindo padrões no check-in e reflexões sobre ruminação, estudo, ritmo circadiano.',
        pergunta: 'O que especificamente te impede de dormir 7h de forma consistente — não em teoria, mas na sua vida real agora? Separa o que é estrutural (plantões) do que é comportamental (suas escolhas).',
        modos: ['escrever', 'lista'],
        placeholder_escrever: 'Seja específico. "Não tenho tempo" é o início da resposta, não o fim.',
        placeholder_lista: 'Liste as barreiras. Para cada uma: estrutural ou comportamental? Se comportamental, qual seria a menor mudança testável?',
        hint: 'A distinção entre o que é fora do seu controle e o que é escolha é o ponto mais importante dessa reflexão.',
      },
      tcc: {
        titulo: 'Barreiras cognitivas para mudança',
        campos: ['Pensamento que justifica a barreira', 'Crença central', 'O menor experimento possível', 'Evidência a favor que já existe'],
        placeholders: [
          'Ex: "Não adianta, meu plantão vai bagunçar tudo"...',
          'Ex: "Não tenho controle sobre minha vida agora"...',
          'Se você fosse testar uma mudança de 10%, sem compromisso, o que seria?',
          'Alguma vez você dormiu bem mesmo numa semana difícil? O que estava diferente?',
        ],
        hint: 'O objetivo é identificar onde há margem real que você talvez esteja subestimando.',
      },
      materiais: [
        { tipo: 'capitulo', titulo: 'Hábitos Atômicos — Cap. 8: Como tornar os hábitos bons mais fáceis', detalhe: 'James Clear · Redução de fricção aplicada às barreiras que você mapeou hoje', principal: true },
        { tipo: 'podcast', titulo: 'Huberman Lab — Sleep Toolkit: Tools for Optimizing Sleep & Wake', detalhe: 'Andrew Huberman · Toolkit prático completo baseado em evidência', principal: false },
      ],
      conceito_revisao: '7h é piso fisiológico — "funcionar com menos" é viés de percepção',
    },
    {
      numero: 6,
      titulo: 'O preço invisível do plantão noturno',
      subtitulo: 'Disrupção circadiana crônica e o que ela faz no longo prazo',
      aula: 'Aula 104 · O sono de quem trabalha em turnos — e como manejar (31 min)',
      resumo: 'Trabalhadores em turnos — categoria que inclui residentes — têm risco elevado de depressão, síndrome metabólica e comprometimento cognitivo cumulativo. A disrupção circadiana crônica não é só cansaço: ela desregula a expressão gênica em praticamente todos os tecidos do corpo. Eslen apresenta estratégias reais de mitigação para quem não pode simplesmente "dormir mais cedo".',
      ancora: {
        badge: 'Semana 1',
        titulo: 'Disrupção circadiana crônica — dano que se acumula silenciosamente',
        desc: 'Diferente da privação aguda (que você sente), a disrupção circadiana crônica acumula dano sem alarme óbvio. A questão não é "vou sobreviver a essa semana" — é o que o padrão de anos de plantão noturno faz na saúde metabólica e cognitiva. Isso não é argumento para pânico — é argumento para estratégias de mitigação intencionais ao longo da carreira.',
      },
      artigo: {
        nome: 'Practice Parameters for Circadian Rhythm Sleep Disorders',
        fonte: 'Morgenthaler et al. · <em>Sleep</em> / AASM, 2007',
        focal: 'Foque nas <strong>estratégias de mitigação para trabalhadores em turno</strong> — luz estratégica, âncoras de sono, gestão de cafeína. A parte clínica é menos relevante que o manejo prático.',
        frase: '"Circadian misalignment produces broad physiological consequences beyond sleep disruption itself."',
        frase_fonte: 'Morgenthaler et al., 2007',
      },
      reflexao: {
        contexto: 'Você está numa das fases mais intensas da formação médica. Plantões noturnos são parte estrutural da rotina — não vão mudar no curto prazo. A pergunta não é como evitar, mas como manejar com inteligência.',
        pergunta: 'Que estratégias de mitigação fazem sentido na sua realidade específica? O que você consegue controlar antes, durante e depois de um plantão noturno?',
        modos: ['escrever', 'lista'],
        placeholder_escrever: 'Antes do plantão / durante / depois. O que é realisticamente possível?',
        placeholder_lista: 'Protocolo pessoal de plantão — estratégias antes, durante e depois.',
        hint: 'Realismo, não idealismo. Uma estratégia que você vai usar vale mais que dez que você vai ignorar.',
      },
      tcc: null,
      materiais: [
        { tipo: 'livro', titulo: 'Por Que Dormimos — Walker · Capítulo 7', detalhe: 'Sobre privação, turnos e o que acontece no longo prazo', principal: true },
        { tipo: 'video', titulo: 'Why Sleep Deprivation Kills — TED-Ed', detalhe: '6 min · Animação · Síntese visual dos mecanismos de dano', principal: false },
      ],
      conceito_revisao: 'Disrupção circadiana crônica acumula dano — mitigação é necessária e possível',
    },
    {
      numero: 7,
      titulo: 'O que ficou dessa semana',
      subtitulo: 'Integrar é mais importante do que acumular — e mais raro',
      aula: 'Dia de integração — sem aula nova',
      resumo: 'Você estudou a neurobiologia do sono ao longo de 6 dias: a desconexão PFC-amígdala, a ruminação, a consolidação de memória, o ritmo circadiano, as barreiras reais e o impacto do plantão noturno. Hoje não há conteúdo novo. Hoje é sobre integrar, nomear o que ficou e definir uma mudança concreta.',
      ancora: {
        badge: 'Semana 1',
        titulo: 'Integração — o aprendizado acontece na síntese',
        desc: 'Acumular informação sem integrar é o equivalente cognitivo de comer sem digerir. A reflexão de hoje não é um exercício a mais — é o momento em que os 6 dias anteriores se tornam conhecimento de fato.',
      },
      artigo: {
        nome: 'Revisão dos artigos da semana',
        fonte: 'Krause (2017) · Scullin (2019) · Walker & Stickgold (2006) · Watson (2015) · Morgenthaler (2007)',
        focal: 'Releia as frases que você carregou durante a semana. Qual delas ficou mais? Qual você resistiu? Qual mudou alguma coisa na sua forma de pensar?',
        frase: '"O sono não é o preço que pagamos pela vigília. É o investimento que torna a vigília valer a pena."',
        frase_fonte: 'Matthew Walker — Por Que Dormimos',
      },
      reflexao: {
        contexto: 'Você chegou ao último dia da semana 1. Olha para os check-ins que preencheu ao longo da semana.',
        pergunta: 'Qual conceito dessa semana mais te afetou — e por quê? O que você vai fazer diferente a partir de agora? (1 coisa concreta — não uma lista)',
        modos: ['escrever'],
        placeholder_escrever: 'Quanto mais específico e menor for a mudança, maior a chance de acontecer. "Vou dormir melhor" não conta. "Vou apagar o celular às 23h" conta.',
        hint: 'Uma mudança concreta vale mais que dez intenções vagas.',
      },
      tcc: null,
      materiais: [
        { tipo: 'livro', titulo: 'Por Que Dormimos — Walker · Introdução + Caps. 1 e 2', detalhe: 'Se ainda não leu, essa é a leitura de fim de semana — o livro mais importante sobre sono escrito para leigos', principal: true },
      ],
      conceito_revisao: 'Integração — o aprendizado acontece na síntese, não na acumulação',
    },
  ],

  reflexao_semanal: {
    titulo: 'Sono como fundação — o que ficou',
    subtitulo: 'Aprofundamento antes de avançar para a Semana 2',
    secoes: [
      {
        titulo: '1. Padrão do check-in',
        prompt: 'Olhe para os check-ins dos 7 dias. Tem algum padrão entre sono, energia e humor? O que os dados dizem que você talvez não tenha notado no dia a dia?',
        placeholder: 'Descreve o padrão — mesmo que seja "não há padrão claro ainda".',
      },
      {
        titulo: '2. Crenças centrais e sono',
        prompt: 'O que as crenças que apareceram no TCC têm em comum? De onde vêm — família, escola de medicina, cultura da residência?',
        placeholder: 'Explore a origem. "Preciso ser produtivo sempre" — quando você aprendeu isso?',
      },
      {
        titulo: '3. O que o sistema da residência te ensina sobre sono',
        prompt: 'Há uma cultura institucional da medicina sobre sono e sacrifício. O que você quer explicitamente rejeitar dessa cultura?',
        placeholder: 'Seja honesto — o que você quer fazer diferente conscientemente?',
      },
      {
        titulo: '4. Uma mudança concreta para a próxima semana',
        prompt: 'Não uma lista. Uma coisa. A menor mudança possível que, se sustentada, teria impacto real. Com condição de implementação.',
        placeholder: 'Ex: "Nas noites sem plantão, vou apagar o celular às 23h. Se não conseguir, vou registrar o motivo."',
      },
      {
        titulo: '5. O que levar para a Semana 2 — Hábitos + Procrastinação',
        prompt: 'O que dessa semana de sono se conecta com hábitos e procrastinação? O que você já antecipa que vai ser desafiador?',
        placeholder: 'Conexões, antecipações, perguntas que você já tem antes de começar a semana 2.',
      },
    ],
  },
};
